# angular-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-frontend
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      containers:
        - name: angular-frontend
          image: yandjoumbi/angular-python-frontend:2
          ports:
            - containerPort: 4200
          env:
            - name: FLASK_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FLASK_BACKEND_URL

---
# angular-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: angular-frontend-service
spec:
  selector:
    app: angular-frontend
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
  type: LoadBalancer  # Exposing it to the external world
