version: '3'
services:
  frontend:
    build: ./angular-frontend # Path to the Angular frontend Dockerfile
    ports:
      - "4200:4200"
    networks:
      - app-network

  backend:
    build: ./python-backend  # Path to the Flask backend Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
