name: Build Packer ubuntu AMI

on:
  workflow_dispatch:
  push:
    branches:
      - yannick

jobs:
  build-ami:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up AWS credentials for Packer
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # Step 3: Install Packer
      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install -y packer

      # Step 4: Build AMI with Packer
      - name: Build AMI
        run: |
          packer init angular-python/packer
          packer fmt angular-python/packer/*.pkr.hcl
          packer validate angular-python/packer/*.pkr.hcl
          packer build angular-python/packer/ubuntu-base-ami.pkr.hcl




